# Generated by Django 4.1.1 on 2023-02-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='dyno/static/'),
        ),
    ]
