# Generated by Django 4.1.1 on 2023-02-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyno', '0004_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='dyno/static/')),
            ],
        ),
    ]
